general:
    folder_output: outputs
    fname_output: blade_out
design_variables:
    blade:
        aero_shape:
            L/D:
                flag: True             # Flag to optimize
                n_opt: 4               # Number of control points along blade span
                max_decrease: 40.
                max_increase: 40.
                index_start: 2         # Lock the first two DVs from blade root
                index_end: 3
                
merit_figure: Cp
                
driver:
  design_of_experiments:
    flag: True            # Flag to enable design of experiments
    run_parallel: False    # Flag to run using parallel processing
    generator: FullFact    # Type of input generator. (Uniform)
    num_samples: 21        # number of samples for (Uniform only)
    debug_print: True

recorder:
    flag: True             # Flag to activate OpenMDAO recorder
    file_name: log_opt.sql # Name of OpenMDAO recorder
