general:
    folder_output: outputs
    fname_output: blade_out
design_variables:
    blade:
        aero_shape:
            L/D:
                flag: True             # Flag to optimize
                n_opt: 6               # Number of control points along blade span
                max_decrease: 20.
                max_increase: 20.
                index_start: 2         # Lock the first two DVs from blade root
                index_end: 6
                
merit_figure: Cp
                
driver:
    optimization:
        flag: True         # Flag to enable optimization
        tol: 1.e-6          # Optimality tolerance
        solver: GA       # Optimization solver. Other options are 'SLSQP' - 'CONMIN'
        step_size: 1.e-5    # Step size for finite differencing
        form: forward       # Finite differencing mode, either forward or central
        debug_print: True

recorder:
    flag: True             # Flag to activate OpenMDAO recorder
    file_name: log_opt.sql # Name of OpenMDAO recorder
